### ISSUE TITLE
Any chance to get the same cfg as the gif shows?

### ISSUE THREAD

**Issue by TempheX** [Kazzaky/AccelHud#1]
Already downloaded the accelhud.cfg to execute it, but looks like a mess and sadly I don't get how it looks(i'm pretty ignorant lol)
![shot-20230226-203227](https://user-images.githubusercontent.com/52763917/221447534-3bca3a65-89b1-4baa-be08-96e868aab550.jpg)

**Comment by Kazzaky** [comment]
Config at accelhud.cfg is meant to be like a feature demo, which should be further configured, by reading readme config option description, play around with the values till it suits your own needs.

The gif config would look something like:
```
seta p_accel 0b000100001
seta p_accel_trueness 0b0010
seta p_accel_neg_mode 1
seta p_accel_yh 180 15
seta p_accel_p_sm 0
seta p_accel_p_fm 0
seta p_accel_p_nk 0
seta p_accel_p_strafe 0
seta p_accel_p_opposite 0
seta p_accel_p_cj 0
seta p_accel_cond_size 5
seta p_accel_rgba ".2 .9 .2 .8"
seta p_accel_neg_rgba ".9 .2 .2 .8"
```

**Comment by TempheX** [comment]
Nice! Thank you...

Other question is how the snaps zones did get colored when you where pointing at it in the gif?

Sorry for the inconvinience... I find this hud hard to set up.

**Comment by Kazzaky** [comment]
`mdd_snap 0bxxx1x` in case you need help with proxymod cvars type `mdd_help mdd_snap` or whatever else command to display description
